import 'package:flutter/material.dart';

class AppLocalizations {
  final bool isArabic;

  AppLocalizations(this.isArabic);

  static AppLocalizations of(BuildContext context) {
    // Falls back to simple local state lookup or provider-based state lookup
    final localizations = Localizations.of<AppLocalizations>(context, AppLocalizations);
    return localizations ?? AppLocalizations(false);
  }

  TextDirection get textDirection => isArabic ? TextDirection.rtl : TextDirection.ltr;
  TextAlign get textAlign => isArabic ? TextAlign.right : TextAlign.left;
  Alignment get alignment => isArabic ? Alignment.centerRight : Alignment.centerLeft;

  String translate(String key) {
    if (isArabic) {
      return _arabicValues[key] ?? key;
    }
    return _englishValues[key] ?? key;
  }

  static const Map<String, String> _englishValues = {
    'appName': 'MilStock',
    'appSubtitle': 'Military Logistics Command',
    'slogan': 'Precision Inventory Control for Military Operations',
    'sloganDetails': 'Secure and real-time tracking of essential supplies and logistical assets across all units and warehouses.',
    'badgeSecure': 'Secure Access',
    'badgeRole': 'Role-Based Control',
    'badgeAnalytics': 'Real-Time Analytics',
    
    // Login Screen
    'loginTitle': 'Welcome Back',
    'loginSub': 'Sign in to access your command center',
    'emailOrUsername': 'Email or Username',
    'emailPlaceholder': 'Enter your email or username',
    'password': 'Password',
    'passwordPlaceholder': 'Enter your password',
    'rememberMe': 'Remember me',
    'forgotPassword': 'Forgot password?',
    'signInButton': 'Sign In to MilStock',
    'demoCredentials': 'DEMO CREDENTIALS',
    'demoAdmin': 'Admin',
    'demoUser': 'Unit User',
    'demoPasswordInfo': 'Password: any value',
    'switchLanguage': 'التبديل إلى العربية',
    'loginError': 'Invalid email or password',

    // Dashboard Screen
    'dashboard': 'Dashboard',
    'activeRequests': 'Active Requests',
    'pendingApproval': 'Pending Approval',
    'completedThisMonth': 'Completed This Month',
    'approvedToday': '1 approved today',
    'processingEst': 'Est. 18h processing',
    'vsLastMonth': '+3 vs last month',
    'stockLevelTitle': 'Stock Level — This Week',
    'capacityPercentage': '% of capacity',
    'recentRequests': 'Recent Requests',
    'viewAll': 'View All',
    'criticalAlerts': 'Critical Alerts',
    'notifications': 'Notifications',
    'unreadNotifications': 'unread notification',
    'markAllAsRead': 'Mark all as read',
    'allNotifications': 'All Notifications',
    'unread': 'Unread',
    'all': 'All',
    'inventory': 'Inventory',
    'validity': 'Validity',
    'system': 'System',
    'priorityNormal': 'NORMAL',
    'priorityHigh': 'HIGH',
    'priorityUrgent': 'URGENT',
    'dashboardOverview': 'Overview of stock status and operations',
    'copyright': '© 2026 MilStock. All rights reserved.',
    'error': 'Error',
    'notes': 'Notes',
    'noNotes': 'No notes available.',
    'confirmDelete': 'Confirm Delete',
    'confirmDeleteMessage': 'Are you sure you want to delete {name}? This action cannot be undone.',
    'delete': 'Delete',
    'msgLowStock': 'Medical supplies at Warehouse B are below threshold (15 items remaining)',
    'msgExpiration': '23 items will expire within the next 7 days',
    'msgApproved': 'Your request REQ-1230 has been approved and will be delivered on 2026-05-05',
    'msgAudit': 'Monthly inventory audit has been completed successfully',
    'msgReview': 'Your request REQ-1228 is currently being reviewed by the warehouse manager',
    'time5m': '5 minutes ago',
    'time1h': '1 hour ago',
    'time2h': '2 hours ago',
    'time5h': '5 hours ago',
    'time1d': '1 day ago',
    'mon': 'Mon',
    'tue': 'Tue',
    'wed': 'Wed',
    'thu': 'Thu',
    'fri': 'Fri',
    'sat': 'Sat',
    'sun': 'Sun',
    'catAll': 'All',
    'catFood': 'Food',
    'catMedical': 'Medical',
    'catSupplies': 'Supplies',
    'catEquipment': 'Equipment',
    'itemMre': 'Ready-to-eat Meals (MRE)',
    'itemFirstAid': 'First Aid Kit',
    'itemBoots': 'Military Boots',
    'itemMedicalEquip': 'Medical Equipment',
    'itemMreX500': 'Ready-to-eat Meals (MRE) x 500',
    'itemMedicalEquipX200': 'Medical Equipment x 200',
    'unitFirstCompany': 'First Company',
    'unitInfantry': 'Infantry Battalion',
    'time10m': '10 minutes ago',
    'time15m': '15 minutes ago',
    'time1hAgo': '1 hour ago',
    'whA': 'Warehouse A',
    'whB': 'Warehouse B',
    'whC': 'Warehouse C',
    'invalidNumber': 'Enter a valid number',
    'notificationsSubtitle': 'Stay updated on inventory alerts and request status',
    'markAllRead': 'Mark All Read',
    'newBadge': 'New',
    'notificationLowStock': 'Low Stock Alert',
    'notificationExpiration': 'Expiration Warning',
    'notificationApproved': 'Request Approved',
    'notificationSystem': 'System Update',
    'notificationReview': 'Request Under Review',
    'profileSubtitle': 'Manage your personal information and account settings',
    'rank': 'Major',
    'employeeId': 'Employee ID',
    'accountStatus': 'Account Status',
    'active': 'Active',
    'personalInfo': 'Personal Information',
    'edit': 'Edit',
    'save': 'Save',
    'saveSuccess': 'Changes saved successfully',
    'actLogin': 'Login',
    'actApproval': 'Approval of request REQ-1233',
    'actExport': 'Export monthly report',
    'actSecurity': 'Change security settings',
    'fullName': 'Full Name',
    'email': 'Email',
    'phoneNumber': 'Phone Number',
    'militaryUnit': 'Military Unit',
    'militaryUnitValue': 'Central Command',
    'changePassword': 'Change Password',
    'currentPassword': 'Current Password',
    'newPassword': 'New Password',
    'confirmPassword': 'Confirm New Password',
    'updatePassword': 'Update Password',
    'recentActivity': 'Recent Activity',
    'searchPlaceholder': 'Search by item name or ID...',
    
    // Inventory Management
    'inventoryManagement': 'Inventory Management',
    'inventorySubtitle': 'Track and manage all inventory items across warehouses',
    'addNewItem': 'Add New Item',
    'itemId': 'ITEM ID',
    'itemName': 'ITEM NAME',
    'category': 'CATEGORY',
    'quantity': 'QUANTITY',
    'status': 'STATUS',
    'lastUpdated': 'LAST UPDATED',
    'warehouse': 'WAREHOUSE',
    'action': 'ACTION',
    'filters': 'Filters',
    'export': 'Export',
    
    // Status badges
    'inStock': 'In Stock',
    'lowStock': 'Low Stock',
    'outOfStock': 'Out of Stock',
    'pending': 'Pending',
    'approved': 'Approved',
    'delivered': 'Delivered',

    // Add Item Dialog
    'addItemTitle': 'Add New Inventory Item',
    'basicInfo': 'Basic Information',
    'stockInfo': 'Stock Information',
    'locationStorage': 'Location & Storage',
    'expirationTracking': 'Expiration & Tracking',
    'additionalDetails': 'Additional Details',
    'serialNumber': 'Serial Number',
    'serialNumberPlaceholder': 'Enter serial number',
    'itemNameLabel': 'Item Name',
    'itemNamePlaceholder': 'e.g. MRE Rations Type A',
    'categoryLabel': 'Category',
    'quantityLabel': 'Initial Quantity',
    'quantityPlaceholder': 'e.g. 500',
    'warehouseLabel': 'Warehouse Location',
    'warehousePlaceholder': 'Select Warehouse',
    'expiryDateLabel': 'Expiry Date',
    'expiryDatePlaceholder': 'YYYY-MM-DD',
    'manufacturerLabel': 'Manufacturer/Supplier',
    'manufacturerPlaceholder': 'e.g. Alpha Company',
    'additionalNotes': 'Notes',
    'additionalNotesPlaceholder': 'Add any additional notes...',
    'saveItemButton': 'Save Item',
    'cancelButton': 'Cancel',
    'successAddItem': 'Item added successfully',

    // Sidebar items
    'menuDashboard': 'Dashboard',
    'menuInventory': 'Inventory',
    'menuRequests': 'My Requests',
    'menuSettings': 'Settings',
    'menuProfile': 'Profile',
    'menuLogout': 'Logout',
    'menuConsumption': 'Consumption & Waste',
    
    // Demographics
    'roleAdmin': 'Admin / Command',
    'roleUser': 'User / Requester',
    'averageProcessingTime': 'Avg. Processing Time',
    'averageHours': '18 Hrs',
    'hoursChange': '-2 hours from last week',
  };

  static const Map<String, String> _arabicValues = {
    'appName': 'ميلستوك',
    'appSubtitle': 'قيادة اللوجستيات العسكرية',
    'slogan': 'إدارة المخزون العسكري بدقة عالية وكفاءة استثنائية',
    'sloganDetails': 'تتبع أمني وفوري للإمدادات الأساسية والمستلزمات اللوجستية عبر جميع الوحدات والمستودعات.',
    'badgeSecure': 'وصول آمن',
    'badgeRole': 'تحكم بالأدوار',
    'badgeAnalytics': 'تحليلات فورية',

    // Login Screen
    'loginTitle': 'مرحباً بعودتك',
    'loginSub': 'سجل دخولك للوصول إلى لوحة القيادة',
    'emailOrUsername': 'البريد الإلكتروني أو اسم المستخدم',
    'emailPlaceholder': 'أدخل بريدك الإلكتروني أو اسم المستخدم',
    'password': 'كلمة المرور',
    'passwordPlaceholder': 'أدخل كلمة المرور',
    'rememberMe': 'تذكرني',
    'forgotPassword': 'نسيت كلمة المرور؟',
    'signInButton': 'تسجيل الدخول إلى MilStock',
    'demoCredentials': 'بيانات تجريبية',
    'demoAdmin': 'مسؤول',
    'demoUser': 'مستخدم',
    'demoPasswordInfo': 'كلمة المرور: أي كلمة',
    'switchLanguage': 'Switch to English',
    'loginError': 'البريد الإلكتروني أو كلمة المرور غير صالحة',

    // Dashboard Screen
    'dashboard': 'لوحة القيادة',
    'activeRequests': 'الطلبات النشطة',
    'pendingApproval': 'في انتظار الموافقة',
    'completedThisMonth': 'المكتملة هذا الشهر',
    'approvedToday': 'تمت الموافقة على 1 اليوم',
    'processingEst': 'المعالجة المتوقعة 18 ساعة',
    'vsLastMonth': '+3 مقارنة بالشهر الماضي',
    'stockLevelTitle': 'مستوى المخزون — هذا الأسبوع',
    'capacityPercentage': '% من السعة',
    'recentRequests': 'الطلبات الأخيرة',
    'viewAll': 'عرض الكل',
    'criticalAlerts': 'تنبيهات حرجة',
    'notifications': 'الإشعارات',
    'unreadNotifications': 'إشعار غير مقروء',
    'markAllAsRead': 'تعليم الكل كمقروء',
    'allNotifications': 'جميع الإشعارات',
    'unread': 'غير المقروءة',
    'all': 'الكل',
    'inventory': 'المخزون',
    'validity': 'الصلاحية',
    'system': 'النظام',
    'priorityNormal': 'عادي',
    'priorityHigh': 'عالي',
    'priorityUrgent': 'عاجل',
    'dashboardOverview': 'نظرة عامة على حالة المخزون والعمليات',
    'copyright': '© 2026 ميلستوك. جميع الحقوق محفوظة.',
    'error': 'خطأ',
    'notes': 'ملاحظات',
    'noNotes': 'لا توجد ملاحظات متاحة.',
    'confirmDelete': 'تأكيد الحذف',
    'confirmDeleteMessage': 'هل أنت متأكد من حذف {name}؟ لا يمكن التراجع عن هذا الإجراء.',
    'delete': 'حذف',
    'msgLowStock': 'مستوى المستلزمات الطبية في المستودع B أصبح دون الحد الأدنى (15 صنفاً متبقياً)',
    'msgExpiration': '23 صنفاً ستنتهي صلاحيتها خلال الـ 7 أيام القادمة',
    'msgApproved': 'تمت الموافقة على طلبك REQ-1230 وسيتم التسليم في 2026-05-05',
    'msgAudit': 'تم إكمال تدقيق المخزون الشهري بنجاح',
    'msgReview': 'طلبك REQ-1228 قيد المراجعة حالياً من قبل مدير المستودع',
    'time5m': 'قبل 5 دقائق',
    'time1h': 'قبل ساعة',
    'time2h': 'قبل ساعتين',
    'time5h': 'قبل 5 ساعات',
    'time1d': 'منذ يوم',
    'mon': 'الإثنين',
    'tue': 'الثلاثاء',
    'wed': 'الأربعاء',
    'thu': 'الخميس',
    'fri': 'الجمعة',
    'sat': 'السبت',
    'sun': 'الأحد',
    'catAll': 'الكل',
    'catFood': 'طعام',
    'catMedical': 'طبي',
    'catSupplies': 'مستلزمات',
    'catEquipment': 'معدات',
    'itemMre': 'وجبات جاهزة (MRE)',
    'itemFirstAid': 'حقيبة إسعافات أولية',
    'itemBoots': 'أحذية عسكرية',
    'itemMedicalEquip': 'معدات طبية',
    'itemMreX500': 'وجبات جاهزة x 500',
    'itemMedicalEquipX200': 'معدات طبية x 200',
    'unitFirstCompany': 'السرية الأولى',
    'unitInfantry': 'كتيبة المشاة',
    'time10m': 'منذ 10 دقائق',
    'time15m': 'منذ 15 دقيقة',
    'time1hAgo': 'منذ ساعة',
    'whA': 'المستودع أ',
    'whB': 'المستودع ب',
    'whC': 'المستودع ج',
    'invalidNumber': 'أدخل رقماً صالحاً',
    'notificationsSubtitle': 'ابقَ على اطلاع على تنبيهات المخزون وحالة الطلبات',
    'markAllRead': 'تعليم الكل كمقروء',
    'newBadge': 'جديد',
    'notificationLowStock': 'تنبيه انخفاض المخزون',
    'notificationExpiration': 'تحذير انتهاء الصلاحية',
    'notificationApproved': 'تمت الموافقة على الطلب',
    'notificationSystem': 'تحديث النظام',
    'notificationReview': 'طلب قيد المراجعة',
    'profileSubtitle': 'إدارة معلوماتك الشخصية وإعدادات الحساب',
    'rank': 'مقدم',
    'employeeId': 'رقم الموظف',
    'accountStatus': 'حالة الحساب',
    'active': 'نشط',
    'personalInfo': 'المعلومات الشخصية',
    'edit': 'تعديل',
    'save': 'حفظ',
    'saveSuccess': 'تم حفظ التعديلات بنجاح',
    'actLogin': 'تسجيل دخول',
    'actApproval': 'الموافقة على طلب REQ-1233',
    'actExport': 'تصدير تقرير شهري',
    'actSecurity': 'تغيير إعدادات الأمان',
    'fullName': 'الاسم الكامل',
    'email': 'البريد الإلكتروني',
    'phoneNumber': 'رقم الهاتف',
    'militaryUnit': 'الوحدة العسكرية',
    'militaryUnitValue': 'القيادة المركزية',
    'changePassword': 'تغيير كلمة المرور',
    'currentPassword': 'كلمة المرور الحالية',
    'newPassword': 'كلمة المرور الجديدة',
    'confirmPassword': 'تأكيد كلمة المرور الجديدة',
    'updatePassword': 'تحديث كلمة المرور',
    'recentActivity': 'النشاط الأخير',
    'searchPlaceholder': 'البحث باسم العنصر أو الرقم التعريفي...',

    // Inventory Management
    'inventoryManagement': 'إدارة المخزون',
    'inventorySubtitle': 'تتبع وإدارة جميع عناصر المخزون عبر المستودعات والمخازن',
    'addNewItem': 'إضافة عنصر جديد +',
    'itemId': 'رقم العنصر',
    'itemName': 'اسم العنصر',
    'category': 'الفئة',
    'quantity': 'الكمية',
    'status': 'الحالة',
    'lastUpdated': 'آخر تحديث',
    'warehouse': 'المستودع',
    'action': 'الإجراء',
    'filters': 'تصفية',
    'export': 'تصدير',

    // Status badges
    'inStock': 'متوفر',
    'lowStock': 'مخزون منخفض',
    'outOfStock': 'نفذ المخزون',
    'pending': 'قيد الانتظار',
    'approved': 'موافق عليه',
    'delivered': 'تم التسليم',

    // Add Item Dialog
    'addItemTitle': 'إضافة عنصر مخزون جديد',
    'basicInfo': 'المعلومات الأساسية',
    'stockInfo': 'معلومات المخزون',
    'locationStorage': 'الموقع والتخزين',
    'expirationTracking': 'الصلاحية والتتبع',
    'additionalDetails': 'تفاصيل إضافية',
    'serialNumber': 'الرقم التسلسلي',
    'serialNumberPlaceholder': 'أدخل الرقم التسلسلي',
    'itemNameLabel': 'اسم العنصر',
    'itemNamePlaceholder': 'مثال: وجبات جاهزة فئة أ',
    'categoryLabel': 'الفئة',
    'quantityLabel': 'الكمية الأولية',
    'quantityPlaceholder': 'مثال: 500',
    'warehouseLabel': 'موقع المستودع',
    'warehousePlaceholder': 'اختر المستودع',
    'expiryDateLabel': 'تاريخ انتهاء الصلاحية',
    'expiryDatePlaceholder': 'YYYY-MM-DD',
    'manufacturerLabel': 'الشركة المصنعة / المورد',
    'manufacturerPlaceholder': 'مثال: شركة ألفا',
    'additionalNotes': 'ملاحظات',
    'additionalNotesPlaceholder': 'أضف أي ملاحظات إضافية...',
    'saveItemButton': 'حفظ العنصر',
    'cancelButton': 'إلغاء',
    'successAddItem': 'تم إضافة العنصر بنجاح',

    // Sidebar items
    'menuDashboard': 'لوحة القيادة',
    'menuInventory': 'المخزون',
    'menuRequests': 'طلباتي',
    'menuSettings': 'الإعدادات',
    'menuProfile': 'الملف الشخصي',
    'menuLogout': 'تسجيل الخروج',
    'menuConsumption': 'الاستهلاك والهدر',

    // Demographics
    'roleAdmin': 'مسؤول / القيادة العامة',
    'roleUser': 'مستخدم / مقدم الطلب',
    'averageProcessingTime': 'متوسط وقت المعالجة',
    'averageHours': '18 ساعة',
    'hoursChange': 'ساعتين أقل من الأسبوع الماضي',
  };
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  final bool isArabic;

  const AppLocalizationsDelegate(this.isArabic);

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(isArabic);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => true;
}
